### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by const** [rjz/typescript-react-redux#14] opened 2017-05-08 02:05 UTC
I'm trying to build sample on Windows 10 and I'm getting build failure on step `npm run build` of readme.md.

npm@4.2.0
node@v7.10.0

The tests apprently worked, but then I got multiple errors. The attached are build log (stderr + stdout) and diagnostic from npm.

[build.txt](https://github.com/rjz/typescript-react-redux/files/982170/build.txt)
[2017-05-08T01_55_37_090Z-debug.log.txt](https://github.com/rjz/typescript-react-redux/files/982175/2017-05-08T01_55_37_090Z-debug.log.txt)

**Comment by rjz** [comment] 2017-05-09 04:12
Many thanks for reporting, @const!

It looks like the [last dependency bump](14273631aae1f8c3538bf8a222a4323acceb1ba6) in this project missed a few important parts. https://github.com/rjz/typescript-react-redux/pull/15 fixes them up and enlists CI to help make sure they don't break in future updates!

**Comment by rjz** [comment] 2017-06-13 03:09
Closing, but let's reopen if the issue can be reproduced with #15 merged.

**Closed by rjz** 2017-06-13 03:09 UTC
